spring.application.name=places-api
spring.datasource.initialize=false

spring.datasource.url=jdbc:postgresql://localhost:5432/commercialplace
spring.datasource.username=commercialplace
spring.datasource.password=biped123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update